name: My second workflow
on: 
  push:
    branches:
      - main

jobs:
  MySecondJob:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running my second workflow!"
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Name files in the repository
        run: |
          echo "the repository ${{github.repository}} contains the following files:"
          tree
      - name: Overwrite Markdown
        run: |
          echo "Adding some Markdown content" >> $GITHUB_STEP_SUMMARY
          echo "There was an error, we need to clear the previous Markdown with some new content." > $GITHUB_STEP_SUMMARY
